### ISSUE TITLE
MPI not really used on the readme

### ISSUE THREAD

**Issue by CareF** [PabloPiaggi/Crystallization-of-Silicon#3]
Another thing. I just realized that on the tutorial it's not really parallelized by directly call lmp_mpi (https://lammps.sandia.gov/doc/Run_basics.html) but still working on single node. 
Instead we should run command `mpirun -np 8 $lammpsexe -in start.lmp`

**Comment by PabloPiaggi** [comment]
Sure! The purpose of the tutorial is not to be a comprehensive guide to the use of computer clusters and high performance computing software. Anyway, since it was important to you to have access to the syntax of the command to run lammps with mpi, I might include it in the REAME.md file. Thanks.
